deployment:
  kind: Deployment
image:
  repository: traefik
  tag: "3.0.0"
ports:
  redis:
    port: 6379
    expose:
      default: true
    protocol: TCP
additionalArguments:
  - "--entrypoints.redis.address=:6379"
  - "--providers.kubernetescrd"
  - "--log.level=DEBUG"
  - "--accesslog=true"
volumes:
  - name: redis-cert
    mountPath: /certs
    type: secret
    name: redis-default-cert
service:
  enabled: true
  type: LoadBalancer
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
  spec:
    ports:
      - name: redis
        port: 6379
        protocol: TCP
        targetPort: redis
